In [12]:
import torch
all_indices = torch.load("indices.pt").cuda()
all_indptr = torch.load("indptr.pt").cuda()
k = torch.load("k.pt").cuda()
lmk = torch.load("landmark.pt").cuda()
kv_last_page_len = torch.load("kv_last_page_len.pt").cuda()

In [13]:
print(all_indices)
print(all_indptr)
print(kv_last_page_len)
bs = len(all_indptr) - 1

tensor([  8,  16,  24,  32,   9,  17,  25,  33,  10,  18,  26,  34,  11,  19,
         27,  35,  12,  20,  28,  36,  13,  21,  29,  37,  14,  22,  30,  38,
         15,  23,  31,  39,  40,  48,  56,  64,  72,  41,  49,  57,  65,  73,
         42,  50,  58,  66,  74,  43,  51,  59,  67,  75,  44,  52,  60,  68,
         76,  45,  53,  61,  69,  77,  46,  54,  62,  70,  78,  47,  55,  63,
         71,  79,  80,  88,  96, 104,  81,  89,  97, 105,  82,  90,  98, 106,
         83,  91,  99, 107,  84,  92, 100, 108,  85,  93, 101, 109,  86,  94,
        102, 110,  87,  95, 103, 111], device='cuda:0', dtype=torch.int32)
tensor([  0,   4,   8,  12,  16,  20,  24,  28,  32,  37,  42,  47,  52,  57,
         62,  67,  72,  76,  80,  84,  88,  92,  96, 100, 104],
       device='cuda:0', dtype=torch.int32)
tensor([4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4],
       device='cuda:0', dtype=torch.int32)


In [15]:
for b in range(bs):
    ind = all_indices[all_indptr[b]: all_indptr[b+1]]
    if kv_last_page_len[b] == 4:
        for i in ind:
            k_i = k[i]
            lmk_i = lmk[i]
            assert torch.allclose(lmk_i, k_i.sum(dim=0))
    
    else:
        for i in ind[:-1]:
            k_i = k[i]
            lmk_i = lmk[i]
            assert torch.allclose(lmk_i, k_i.sum(dim=0))
        